tunnel: bae4a13e-77d3-478e-9563-0a3d90c71fcc
credentials-file: C:\Users\123\.cloudflared\bae4a13e-77d3-478e-9563-0a3d90c71fcc.json

ingress:
  # Backend API endpoint
  - hostname: personal.api.daidataly.online
    service: http://127.0.0.1:8000
  # Catch-all rule (required)
  - service: http_status:404
